"""Quality report combining review, lint, validation, audits, and publish gates."""

from __future__ import annotations

from typing import Any

from common import now_utc
from constants import SCHEMA_VERSION


def severity_counts(findings: list[dict[str, Any]]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for finding in findings:
        severity = str(finding.get("severity") or "unknown")
        counts[severity] = counts.get(severity, 0) + 1
    return dict(sorted(counts.items()))


def task_quality(task: dict[str, Any]) -> dict[str, Any]:
    input_contract = task.get("input_contract") or {}
    output_contract = task.get("output_contract") or {}
    return {
        "task_type": task.get("task_type"),
        "verification_status": task.get("verification_status"),
        "has_evidence_refs": bool(task.get("evidence_refs")),
        "has_routing_cues": bool(task.get("routing_cues")),
        "has_required_inputs": bool(input_contract.get("required_from_user")),
        "has_expected_outputs": bool(output_contract.get("expected_outputs")),
        "has_validation": bool(output_contract.get("minimum_validation")),
        "has_refusal_boundaries": bool(task.get("refusal_boundaries")),
        "interface_hint_count": len(task.get("interface_refs_observed", [])),
        "parameter_constraint_count": len(input_contract.get("parameter_constraints_observed", [])),
    }


def scorecard(name: str, status: str, findings: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    findings = findings or []
    return {
        "name": name,
        "status": status,
        "severity_counts": severity_counts(findings),
        "blocking_count": sum(1 for finding in findings if finding.get("severity") == "error"),
    }


def build_quality_report(
    request: dict[str, Any],
    review_result: dict[str, Any],
    lint_report: dict[str, Any],
    artifact_validation: dict[str, Any],
    phase_state_audit: dict[str, Any],
    protocol_compliance_audit: dict[str, Any],
    builder_runtime_audit: dict[str, Any],
    agent_metadata_audit: dict[str, Any],
    public_origin_audit: dict[str, Any],
    module_inventory_audit: dict[str, Any],
    builder_baseline_audit: dict[str, Any],
    skill_package_audit: dict[str, Any],
    request_template_audit: dict[str, Any],
    request_audit: dict[str, Any],
    request_fingerprint: dict[str, Any],
    external_result_contracts: dict[str, Any],
    child_metadata_audit: dict[str, Any],
    child_package_purity_audit: dict[str, Any],
    output_boundary_audit: dict[str, Any],
    skill_update_plan: dict[str, Any],
    skill_update_audit: dict[str, Any],
    forward_test_plan: dict[str, Any],
    agent_rollout_harness: dict[str, Any],
    agent_rollout_audit: dict[str, Any],
    code_fence_audit: dict[str, Any],
    public_safety_audit: dict[str, Any],
    claim_consistency_audit: dict[str, Any],
    biological_claim_boundary_audit: dict[str, Any],
    child_reference_coverage: dict[str, Any],
    source_grounding_audit: dict[str, Any],
    source_fetch_boundary_audit: dict[str, Any],
    routing_metadata_audit: dict[str, Any],
    workflow_invariant_audit: dict[str, Any],
    requirement_coverage: dict[str, Any],
    completion_evidence_audit: dict[str, Any],
    acceptance_handoff: dict[str, Any],
    api_surface_audit: dict[str, Any],
    key_api_coverage_audit: dict[str, Any],
    publish_gate: dict[str, Any],
    discovery_audit: dict[str, Any],
    discovery_match_audit: dict[str, Any],
    discovery_resolution_audit: dict[str, Any],
    review_cursor: dict[str, Any],
    patch_application: dict[str, Any],
    review_remediation_audit: dict[str, Any],
    review_optimizer_state: dict[str, Any],
    patch_safety_audit: dict[str, Any],
    patch_operation_contracts: dict[str, Any],
    candidate_selection_audit: dict[str, Any],
    candidate_promotion_audit: dict[str, Any],
    final_candidate_audit: dict[str, Any],
    candidate_evolution_audit: dict[str, Any],
    review_discipline_audit: dict[str, Any],
    rubric_grounding_audit: dict[str, Any],
    review_trajectory_audit: dict[str, Any],
    task_catalog: dict[str, Any],
    task_partition_decision_log: dict[str, Any],
    task_partition_audit: dict[str, Any],
    source_parse_report: dict[str, Any],
    source_parsing_coverage: dict[str, Any],
    source_parsing_audit: dict[str, Any],
    source_ingestion_audit: dict[str, Any],
    backend_extension_audit: dict[str, Any],
    environment_install_plan: dict[str, Any],
    resource_boundary_audit: dict[str, Any],
    evidence_coverage: dict[str, Any],
    evidence_precedence: dict[str, Any],
    evidence_claim_taxonomy_audit: dict[str, Any],
    execution_trace_validation: dict[str, Any],
    execution_plan: dict[str, Any],
    tutorial_reproduction_plan: dict[str, Any],
    execution_replay_orchestrator: dict[str, Any],
    verification_claim_audit: dict[str, Any],
    contract_traceability: dict[str, Any],
    lineage_graph: dict[str, Any],
    acceptance_suite: dict[str, Any],
    eval_splits: dict[str, Any],
    eval_result_judge: dict[str, Any],
    eval_leakage_audit: dict[str, Any],
    agent_rollout_result_judge: dict[str, Any],
    e2e_acceptance: dict[str, Any],
    smoke_test_plan: dict[str, Any],
    draft_readiness: dict[str, Any],
    grounding_gate: dict[str, Any],
    routing_fixture: dict[str, Any],
    review_prompt_contracts: dict[str, Any],
    review_prompt_materials: dict[str, Any],
    review_prompt_suite_audit: dict[str, Any],
    review_iteration_log: dict[str, Any],
) -> dict[str, Any]:
    tasks = [task_quality(task) for task in task_catalog.get("tasks", [])]
    task_blockers = [
        task["task_type"]
        for task in tasks
        if not (
            task["has_evidence_refs"]
            and task["has_required_inputs"]
            and task["has_expected_outputs"]
            and task["has_validation"]
            and task["has_refusal_boundaries"]
        )
    ]
    scorecards = [
        scorecard("review", review_result.get("status", "unknown"), review_result.get("final_findings", [])),
        scorecard("lint", lint_report.get("status", "unknown"), lint_report.get("findings", [])),
        scorecard("phase_state_audit", phase_state_audit.get("status", "unknown"), phase_state_audit.get("findings", [])),
        scorecard("protocol_compliance_audit", protocol_compliance_audit.get("status", "unknown"), protocol_compliance_audit.get("findings", [])),
        scorecard("child_metadata_audit", child_metadata_audit.get("status", "unknown"), child_metadata_audit.get("findings", [])),
        scorecard("child_package_purity_audit", child_package_purity_audit.get("status", "unknown"), child_package_purity_audit.get("findings", [])),
        scorecard("builder_runtime_audit", builder_runtime_audit.get("status", "unknown"), builder_runtime_audit.get("findings", [])),
        scorecard("agent_metadata_audit", agent_metadata_audit.get("status", "unknown"), agent_metadata_audit.get("findings", [])),
        scorecard("public_origin_audit", public_origin_audit.get("status", "unknown"), public_origin_audit.get("findings", [])),
        scorecard("module_inventory_audit", module_inventory_audit.get("status", "unknown"), module_inventory_audit.get("findings", [])),
        scorecard("builder_baseline_audit", builder_baseline_audit.get("status", "unknown"), builder_baseline_audit.get("findings", [])),
        scorecard("skill_package_audit", skill_package_audit.get("status", "unknown"), skill_package_audit.get("findings", [])),
        scorecard("request_template_audit", request_template_audit.get("status", "unknown"), request_template_audit.get("findings", [])),
        scorecard("request_audit", request_audit.get("status", "unknown"), request_audit.get("findings", [])),
        scorecard("request_fingerprint", request_fingerprint.get("status", "unknown"), request_fingerprint.get("findings", [])),
        scorecard("external_result_contracts", external_result_contracts.get("status", "unknown"), external_result_contracts.get("findings", [])),
        scorecard("draft_readiness", draft_readiness.get("status", "unknown"), draft_readiness.get("findings", [])),
        scorecard("output_boundary_audit", output_boundary_audit.get("status", "unknown"), output_boundary_audit.get("findings", [])),
        scorecard("skill_update_plan", skill_update_plan.get("status", "unknown"), skill_update_plan.get("findings", [])),
        scorecard("skill_update_audit", skill_update_audit.get("status", "unknown"), skill_update_audit.get("findings", [])),
        scorecard("forward_test_plan", forward_test_plan.get("status", "unknown"), forward_test_plan.get("findings", [])),
        scorecard("agent_rollout_harness", agent_rollout_harness.get("status", "unknown"), agent_rollout_harness.get("findings", [])),
        scorecard("agent_rollout_audit", agent_rollout_audit.get("status", "unknown"), agent_rollout_audit.get("findings", [])),
        scorecard("discovery_audit", discovery_audit.get("status", "unknown"), discovery_audit.get("findings", [])),
        scorecard("discovery_match_audit", discovery_match_audit.get("status", "unknown"), discovery_match_audit.get("findings", [])),
        scorecard("discovery_resolution_audit", discovery_resolution_audit.get("status", "unknown"), discovery_resolution_audit.get("findings", [])),
        scorecard("review_prompt_contracts", review_prompt_contracts.get("status", "unknown"), review_prompt_contracts.get("findings", [])),
        scorecard("review_prompt_materials", review_prompt_materials.get("status", "unknown"), review_prompt_materials.get("findings", [])),
        scorecard("review_prompt_suite_audit", review_prompt_suite_audit.get("status", "unknown"), review_prompt_suite_audit.get("findings", [])),
        scorecard("review_iteration_log", review_iteration_log.get("status", "unknown"), review_iteration_log.get("findings", [])),
        scorecard("review_cursor", review_cursor.get("status", "unknown"), review_cursor.get("findings", [])),
        scorecard("patch_application", patch_application.get("status", "unknown"), patch_application.get("findings", [])),
        scorecard("review_remediation_audit", review_remediation_audit.get("status", "unknown"), review_remediation_audit.get("findings", [])),
        scorecard("review_optimizer_state", review_optimizer_state.get("status", "unknown"), review_optimizer_state.get("findings", [])),
        scorecard("patch_safety_audit", patch_safety_audit.get("status", "unknown"), patch_safety_audit.get("findings", [])),
        scorecard("patch_operation_contracts", patch_operation_contracts.get("status", "unknown"), patch_operation_contracts.get("findings", [])),
        scorecard("candidate_selection_audit", candidate_selection_audit.get("status", "unknown"), candidate_selection_audit.get("findings", [])),
        scorecard("candidate_promotion_audit", candidate_promotion_audit.get("status", "unknown"), candidate_promotion_audit.get("findings", [])),
        scorecard("final_candidate_audit", final_candidate_audit.get("status", "unknown"), final_candidate_audit.get("findings", [])),
        scorecard("candidate_evolution_audit", candidate_evolution_audit.get("status", "unknown"), candidate_evolution_audit.get("findings", [])),
        scorecard("review_discipline_audit", review_discipline_audit.get("status", "unknown"), review_discipline_audit.get("findings", [])),
        scorecard("rubric_grounding_audit", rubric_grounding_audit.get("status", "unknown"), rubric_grounding_audit.get("findings", [])),
        scorecard("review_trajectory_audit", review_trajectory_audit.get("status", "unknown"), review_trajectory_audit.get("findings", [])),
        scorecard("task_partition_decision_log", task_partition_decision_log.get("status", "unknown"), task_partition_decision_log.get("findings", [])),
        scorecard("task_partition_audit", task_partition_audit.get("status", "unknown"), task_partition_audit.get("findings", [])),
        scorecard("source_parsing_coverage", source_parsing_coverage.get("status", "unknown"), source_parsing_coverage.get("findings", [])),
        scorecard("source_parsing_audit", source_parsing_audit.get("status", "unknown"), source_parsing_audit.get("findings", [])),
        scorecard("source_ingestion_audit", source_ingestion_audit.get("status", "unknown"), source_ingestion_audit.get("findings", [])),
        scorecard("backend_extension_audit", backend_extension_audit.get("status", "unknown"), backend_extension_audit.get("findings", [])),
        scorecard("environment_install_plan", environment_install_plan.get("status", "unknown"), environment_install_plan.get("findings", [])),
        scorecard("resource_boundary_audit", resource_boundary_audit.get("status", "unknown"), resource_boundary_audit.get("findings", [])),
        scorecard("execution_trace_validation", execution_trace_validation.get("status", "unknown"), execution_trace_validation.get("findings", [])),
        scorecard("verification_claim_audit", verification_claim_audit.get("status", "unknown"), verification_claim_audit.get("findings", [])),
        scorecard("tutorial_reproduction_plan", tutorial_reproduction_plan.get("status", "unknown"), tutorial_reproduction_plan.get("findings", [])),
        scorecard("execution_replay_orchestrator", execution_replay_orchestrator.get("status", "unknown"), execution_replay_orchestrator.get("findings", [])),
        scorecard("evidence_coverage", evidence_coverage.get("status", "unknown"), evidence_coverage.get("findings", [])),
        scorecard("evidence_precedence", evidence_precedence.get("status", "unknown"), evidence_precedence.get("findings", [])),
        scorecard("evidence_claim_taxonomy_audit", evidence_claim_taxonomy_audit.get("status", "unknown"), evidence_claim_taxonomy_audit.get("findings", [])),
        scorecard("contract_traceability", contract_traceability.get("status", "unknown"), contract_traceability.get("findings", [])),
        scorecard("lineage_graph", lineage_graph.get("status", "unknown"), lineage_graph.get("findings", [])),
        scorecard("eval_splits", eval_splits.get("status", "unknown"), eval_splits.get("findings", [])),
        scorecard("eval_result_judge", eval_result_judge.get("status", "unknown"), eval_result_judge.get("findings", [])),
        scorecard("eval_leakage_audit", eval_leakage_audit.get("status", "unknown"), eval_leakage_audit.get("findings", [])),
        scorecard("agent_rollout_result_judge", agent_rollout_result_judge.get("status", "unknown"), agent_rollout_result_judge.get("findings", [])),
        scorecard("e2e_acceptance", e2e_acceptance.get("status", "unknown"), e2e_acceptance.get("findings", [])),
        scorecard("smoke_test_plan", smoke_test_plan.get("status", "unknown"), smoke_test_plan.get("findings", [])),
        scorecard("artifact_validation", artifact_validation.get("status", "unknown"), artifact_validation.get("findings", [])),
        scorecard("code_fence_audit", code_fence_audit.get("status", "unknown"), code_fence_audit.get("findings", [])),
        scorecard("public_safety_audit", public_safety_audit.get("status", "unknown"), public_safety_audit.get("findings", [])),
        scorecard("claim_consistency_audit", claim_consistency_audit.get("status", "unknown"), claim_consistency_audit.get("findings", [])),
        scorecard("biological_claim_boundary_audit", biological_claim_boundary_audit.get("status", "unknown"), biological_claim_boundary_audit.get("findings", [])),
        scorecard("child_reference_coverage", child_reference_coverage.get("status", "unknown"), child_reference_coverage.get("findings", [])),
        scorecard("source_fetch_boundary_audit", source_fetch_boundary_audit.get("status", "unknown"), source_fetch_boundary_audit.get("findings", [])),
        scorecard("routing_metadata_audit", routing_metadata_audit.get("status", "unknown"), routing_metadata_audit.get("findings", [])),
        scorecard("source_grounding_audit", source_grounding_audit.get("status", "unknown"), source_grounding_audit.get("findings", [])),
        scorecard("workflow_invariant_audit", workflow_invariant_audit.get("status", "unknown"), workflow_invariant_audit.get("findings", [])),
        scorecard("requirement_coverage", requirement_coverage.get("status", "unknown"), requirement_coverage.get("findings", [])),
        scorecard("completion_evidence_audit", completion_evidence_audit.get("status", "unknown"), completion_evidence_audit.get("findings", [])),
        scorecard("acceptance_handoff", acceptance_handoff.get("status", "unknown"), acceptance_handoff.get("findings", [])),
        scorecard("api_surface_audit", api_surface_audit.get("status", "unknown"), api_surface_audit.get("findings", [])),
        scorecard("key_api_coverage_audit", key_api_coverage_audit.get("status", "unknown"), key_api_coverage_audit.get("findings", [])),
        scorecard("grounding_gate", grounding_gate.get("status", "unknown"), grounding_gate.get("findings", [])),
        scorecard("publish_gate", publish_gate.get("status", "unknown"), publish_gate.get("findings", [])),
    ]
    has_blockers = bool(task_blockers) or any(card["blocking_count"] for card in scorecards)
    return {
        "schema_version": SCHEMA_VERSION,
        "created_at": now_utc(),
        "package_name": request.get("package_name"),
        "method_name": request.get("method_name") or request.get("package_name"),
        "status": "fail" if has_blockers else "pass",
        "publish_gate_status": publish_gate.get("status"),
        "review_score": review_result.get("final_score", {}),
        "review_iteration_count": len(review_result.get("iterations", [])),
        "review_stop_reason": review_result.get("stop_reason"),
        "builder_runtime_audit_status": {
            "status": builder_runtime_audit.get("status"),
            "skill_dir": builder_runtime_audit.get("skill_dir"),
            "observed_cli_commands": builder_runtime_audit.get("observed_cli_commands", []),
            "template_field_count": builder_runtime_audit.get("template_field_count", 0),
            "finding_count": len(builder_runtime_audit.get("findings", [])),
        },
        "agent_metadata_audit_status": {
            "status": agent_metadata_audit.get("status"),
            "display_name": agent_metadata_audit.get("display_name"),
            "default_prompt_has_skill_token": agent_metadata_audit.get("default_prompt_has_skill_token"),
            "missing_openai_concepts": agent_metadata_audit.get("missing_openai_concepts", []),
            "finding_count": len(agent_metadata_audit.get("findings", [])),
        },
        "public_origin_audit_status": {
            "status": public_origin_audit.get("status"),
            "checked_file_count": public_origin_audit.get("checked_file_count", 0),
            "finding_count": len(public_origin_audit.get("findings", [])),
        },
        "module_inventory_audit_status": {
            "status": module_inventory_audit.get("status"),
            "module_count": module_inventory_audit.get("module_count", 0),
            "required_docs": module_inventory_audit.get("required_docs", []),
            "finding_count": len(module_inventory_audit.get("findings", [])),
        },
        "builder_baseline_audit_status": {
            "status": builder_baseline_audit.get("status"),
            "family_count": builder_baseline_audit.get("family_count", 0),
            "covered_family_count": builder_baseline_audit.get("covered_family_count", 0),
            "module_count": builder_baseline_audit.get("module_count", 0),
            "covered_module_count": builder_baseline_audit.get("covered_module_count", 0),
            "finding_count": len(builder_baseline_audit.get("findings", [])),
        },
        "skill_package_audit_status": {
            "status": skill_package_audit.get("status"),
            "checked_file_count": len(skill_package_audit.get("checked_files", [])),
            "required_files": skill_package_audit.get("required_files", []),
            "finding_count": len(skill_package_audit.get("findings", [])),
        },
        "request_template_audit_status": {
            "status": request_template_audit.get("status"),
            "template_field_count": request_template_audit.get("template_field_count", 0),
            "missing_template_fields": request_template_audit.get("missing_template_fields", []),
            "missing_runtime_required_fields": request_template_audit.get("missing_runtime_required_fields", []),
            "finding_count": len(request_template_audit.get("findings", [])),
        },
        "request_audit_status": {
            "status": request_audit.get("status"),
            "target_agent": request_audit.get("target_agent"),
            "has_supporting_sources": request_audit.get("has_supporting_sources"),
            "execution_grounded_requested": request_audit.get("execution_grounded_requested"),
            "remote_environment_required": request_audit.get("remote_environment_required"),
            "finding_count": len(request_audit.get("findings", [])),
        },
        "request_fingerprint_status": {
            "status": request_fingerprint.get("status"),
            "request_key_count": request_fingerprint.get("request_key_count", 0),
            "stores_raw_request": request_fingerprint.get("stores_raw_request"),
            "sensitive_field_count": len(request_fingerprint.get("sensitive_field_paths", [])),
            "finding_count": len(request_fingerprint.get("findings", [])),
        },
        "external_result_contracts_status": {
            "status": external_result_contracts.get("status"),
            "eval_result_count": external_result_contracts.get("eval_result_count", 0),
            "agent_rollout_result_count": external_result_contracts.get("agent_rollout_result_count", 0),
            "smoke_test_result_count": external_result_contracts.get("smoke_test_result_count", 0),
            "execution_replay_result_count": external_result_contracts.get("execution_replay_result_count", 0),
            "e2e_acceptance_result_count": external_result_contracts.get("e2e_acceptance_result_count", 0),
            "supplied_result_count": external_result_contracts.get("supplied_result_count", 0),
            "finding_count": len(external_result_contracts.get("findings", [])),
        },
        "child_package_purity_audit_status": {
            "status": child_package_purity_audit.get("status"),
            "unexpected_public_files": child_package_purity_audit.get("unexpected_public_files", []),
            "unexpected_public_directories": child_package_purity_audit.get("unexpected_public_directories", []),
            "finding_count": len(child_package_purity_audit.get("findings", [])),
        },
        "biological_claim_boundary_audit_status": {
            "status": biological_claim_boundary_audit.get("status"),
            "risky_claim_count": biological_claim_boundary_audit.get("risky_claim_count", 0),
            "cross_modal_evidence_supported": biological_claim_boundary_audit.get("cross_modal_evidence_supported"),
            "missing_refusal_keys": biological_claim_boundary_audit.get("missing_refusal_keys", []),
            "finding_count": len(biological_claim_boundary_audit.get("findings", [])),
        },
        "phase_state_audit_status": {
            "status": phase_state_audit.get("status"),
            "phase_count": phase_state_audit.get("phase_count", 0),
            "unique_phase_count": phase_state_audit.get("unique_phase_count", 0),
            "output_count": phase_state_audit.get("output_count", 0),
            "finding_count": len(phase_state_audit.get("findings", [])),
        },
        "protocol_compliance_audit_status": {
            "status": protocol_compliance_audit.get("status"),
            "plan_only_artifact_count": protocol_compliance_audit.get("plan_only_artifact_count", 0),
            "plan_only_pass_count": protocol_compliance_audit.get("plan_only_pass_count", 0),
            "protocol_record_count": protocol_compliance_audit.get("protocol_record_count", 0),
            "protocol_pass_count": protocol_compliance_audit.get("protocol_pass_count", 0),
            "finding_count": len(protocol_compliance_audit.get("findings", [])),
        },
        "child_metadata_audit_status": {
            "status": child_metadata_audit.get("status"),
            "task_count": len(child_metadata_audit.get("task_types", [])),
            "top_level_dirs": child_metadata_audit.get("top_level_dirs", []),
            "finding_count": len(child_metadata_audit.get("findings", [])),
        },
        "discovery_audit_status": {
            "status": discovery_audit.get("status"),
            "preflight_decision": discovery_audit.get("preflight_decision"),
            "final_decision": discovery_audit.get("final_decision"),
            "match_count": discovery_audit.get("match_count", 0),
            "finding_count": len(discovery_audit.get("findings", [])),
        },
        "discovery_match_audit_status": {
            "status": discovery_match_audit.get("status"),
            "decision": discovery_match_audit.get("decision"),
            "match_count": discovery_match_audit.get("match_count", 0),
            "best_match_level": (discovery_match_audit.get("best_match") or {}).get("match_level"),
            "best_confidence": (discovery_match_audit.get("best_match") or {}).get("confidence", 0.0),
            "finding_count": len(discovery_match_audit.get("findings", [])),
        },
        "discovery_resolution_audit_status": {
            "status": discovery_resolution_audit.get("status"),
            "preflight_decision": discovery_resolution_audit.get("preflight_decision"),
            "final_decision": discovery_resolution_audit.get("final_decision"),
            "recommended_action": discovery_resolution_audit.get("recommended_action"),
            "ambiguous_high_confidence": discovery_resolution_audit.get("ambiguous_high_confidence"),
            "finding_count": len(discovery_resolution_audit.get("findings", [])),
        },
        "review_cursor_status": {
            "status": review_cursor.get("status"),
            "phase": (review_cursor.get("current") or {}).get("phase"),
            "resumable": (review_cursor.get("current") or {}).get("resumable"),
            "iteration_count": review_cursor.get("iteration_count", 0),
            "finding_count": len(review_cursor.get("findings", [])),
        },
        "review_prompt_suite_audit_status": {
            "status": review_prompt_suite_audit.get("status"),
            "duty_count": review_prompt_suite_audit.get("duty_count", 0),
            "covered_count": review_prompt_suite_audit.get("covered_count", 0),
            "iteration_count": review_prompt_suite_audit.get("iteration_count", 0),
            "finding_count": len(review_prompt_suite_audit.get("findings", [])),
        },
        "review_prompt_materials_status": {
            "status": review_prompt_materials.get("status"),
            "material_count": review_prompt_materials.get("material_count", 0),
            "contract_role_count": review_prompt_materials.get("contract_role_count", 0),
            "finding_count": len(review_prompt_materials.get("findings", [])),
        },
        "patch_application_status": {
            "status": patch_application.get("status"),
            "iteration_count": patch_application.get("iteration_count", 0),
            "changed_iteration_count": patch_application.get("changed_iteration_count", 0),
            "changed_artifacts": patch_application.get("changed_artifacts", []),
            "finding_count": len(patch_application.get("findings", [])),
        },
        "review_remediation_audit_status": {
            "status": review_remediation_audit.get("status"),
            "iteration_count": review_remediation_audit.get("iteration_count", 0),
            "record_count": review_remediation_audit.get("record_count", 0),
            "final_error_count": review_remediation_audit.get("final_error_count", 0),
            "remediation_status_counts": review_remediation_audit.get("remediation_status_counts", {}),
            "finding_count": len(review_remediation_audit.get("findings", [])),
        },
        "review_optimizer_state_status": {
            "status": review_optimizer_state.get("status"),
            "iteration_count": review_optimizer_state.get("iteration_count", 0),
            "strict_improvement_gate": review_optimizer_state.get("strict_improvement_gate"),
            "rejected_edit_count": review_optimizer_state.get("rejected_edit_count", 0),
            "cache_key": review_optimizer_state.get("cache_key"),
        },
        "patch_safety_audit_status": {
            "status": patch_safety_audit.get("status"),
            "patch_action_count": patch_safety_audit.get("patch_action_count", 0),
            "allowed_patch_artifacts": patch_safety_audit.get("allowed_patch_artifacts", []),
            "finding_count": len(patch_safety_audit.get("findings", [])),
        },
        "patch_operation_contracts_status": {
            "status": patch_operation_contracts.get("status"),
            "contract_count": patch_operation_contracts.get("contract_count", 0),
            "action_count": patch_operation_contracts.get("action_count", 0),
            "allowed_artifacts": patch_operation_contracts.get("allowed_artifacts", []),
            "finding_count": len(patch_operation_contracts.get("findings", [])),
        },
        "backend_extension_audit_status": {
            "status": backend_extension_audit.get("status"),
            "requested_backend": backend_extension_audit.get("requested_backend"),
            "implemented_backends": backend_extension_audit.get("implemented_backends", []),
            "reserved_backends": backend_extension_audit.get("reserved_backends", []),
            "finding_count": len(backend_extension_audit.get("findings", [])),
        },
        "candidate_promotion_audit_status": {
            "status": candidate_promotion_audit.get("status"),
            "active_version_id": candidate_promotion_audit.get("active_version_id"),
            "selection_status": candidate_promotion_audit.get("candidate_selection_audit_status"),
            "promoted_to_release": candidate_promotion_audit.get("promoted_to_release"),
            "finding_count": len(candidate_promotion_audit.get("findings", [])),
        },
        "candidate_selection_audit_status": {
            "status": candidate_selection_audit.get("status"),
            "selected_version_id": candidate_selection_audit.get("selected_version_id"),
            "selected_candidate_id": candidate_selection_audit.get("selected_candidate_id"),
            "selection_mode": candidate_selection_audit.get("selection_mode"),
            "finding_count": len(candidate_selection_audit.get("findings", [])),
        },
        "final_candidate_audit_status": {
            "status": final_candidate_audit.get("status"),
            "finalized_for_release": final_candidate_audit.get("finalized_for_release"),
            "active_version_id": final_candidate_audit.get("active_version_id"),
            "release_candidate_version": final_candidate_audit.get("release_candidate_version"),
            "finding_count": len(final_candidate_audit.get("findings", [])),
        },
        "candidate_evolution_audit_status": {
            "status": candidate_evolution_audit.get("status"),
            "active_version_id": candidate_evolution_audit.get("active_version_id"),
            "active_candidate_id": candidate_evolution_audit.get("active_candidate_id"),
            "stage_count": candidate_evolution_audit.get("stage_count", 0),
            "finding_count": len(candidate_evolution_audit.get("findings", [])),
        },
        "review_discipline_audit_status": {
            "status": review_discipline_audit.get("status"),
            "iteration_count": review_discipline_audit.get("iteration_count", 0),
            "stop_reason": review_discipline_audit.get("stop_reason"),
            "finding_count": len(review_discipline_audit.get("findings", [])),
        },
        "review_prompt_contracts_status": {
            "status": review_prompt_contracts.get("status"),
            "contract_count": review_prompt_contracts.get("contract_count", 0),
            "iteration_count": review_prompt_contracts.get("iteration_count", 0),
            "finding_count": len(review_prompt_contracts.get("findings", [])),
        },
        "review_iteration_log_status": {
            "status": review_iteration_log.get("status"),
            "iteration_count": review_iteration_log.get("iteration_count", 0),
            "changed_iteration_count": review_iteration_log.get("changed_iteration_count", 0),
            "finding_count": len(review_iteration_log.get("findings", [])),
        },
        "rubric_grounding_audit_status": {
            "status": rubric_grounding_audit.get("status"),
            "record_count": rubric_grounding_audit.get("record_count", 0),
            "finding_count": len(rubric_grounding_audit.get("findings", [])),
        },
        "review_trajectory_audit_status": {
            "status": review_trajectory_audit.get("status"),
            "iteration_count": review_trajectory_audit.get("iteration_count", 0),
            "finding_count": len(review_trajectory_audit.get("findings", [])),
        },
        "task_partition_audit_status": {
            "status": task_partition_audit.get("status"),
            "task_count": task_partition_audit.get("task_count", 0),
            "tutorial_count": task_partition_audit.get("tutorial_count", 0),
            "ambiguous_pair_count": task_partition_audit.get("ambiguous_pair_count", 0),
            "finding_count": len(task_partition_audit.get("findings", [])),
        },
        "task_partition_decision_log_status": {
            "status": task_partition_decision_log.get("status"),
            "decision_count": task_partition_decision_log.get("decision_count", 0),
            "accepted_decision_count": task_partition_decision_log.get("accepted_decision_count", 0),
            "rejected_tutorial_split_count": task_partition_decision_log.get("rejected_tutorial_split_count", 0),
            "finding_count": len(task_partition_decision_log.get("findings", [])),
        },
        "source_parse_counts": source_parse_report.get("counts", {}),
        "source_parser_capability_summary": {
            "kind_count": len(source_parse_report.get("capability_matrix", [])),
            "execution_verifying_kinds": [
                row.get("kind")
                for row in source_parse_report.get("capability_matrix", [])
                if isinstance(row, dict) and row.get("can_verify_execution") is not False
            ],
            "reserved_extension_kinds": [
                row.get("kind")
                for row in source_parse_report.get("capability_matrix", [])
                if isinstance(row, dict) and row.get("backend_support") == "reserved_extension"
            ],
        },
        "agent_rollout_harness_status": {
            "status": agent_rollout_harness.get("status"),
            "rollout_count": agent_rollout_harness.get("rollout_count", 0),
            "task_count": agent_rollout_harness.get("task_count", 0),
            "missing_task_types": agent_rollout_harness.get("missing_task_types", []),
            "finding_count": len(agent_rollout_harness.get("findings", [])),
        },
        "agent_rollout_audit_status": {
            "status": agent_rollout_audit.get("status"),
            "scenario_count": agent_rollout_audit.get("scenario_count", 0),
            "rollout_count": agent_rollout_audit.get("rollout_count", 0),
            "mapped_scenario_count": agent_rollout_audit.get("mapped_scenario_count", 0),
            "finding_count": len(agent_rollout_audit.get("findings", [])),
        },
        "source_parsing_coverage_status": {
            "status": source_parsing_coverage.get("status"),
            "file_count": source_parsing_coverage.get("file_count", 0),
            "indexed_file_count": source_parsing_coverage.get("indexed_file_count", 0),
            "parseable_file_count": source_parsing_coverage.get("parseable_file_count", 0),
            "api_candidate_count": source_parsing_coverage.get("api_candidate_count", 0),
            "interface_count": source_parsing_coverage.get("interface_count", 0),
            "tutorial_count": source_parsing_coverage.get("tutorial_count", 0),
            "finding_count": len(source_parsing_coverage.get("findings", [])),
        },
        "source_parsing_audit_status": {
            "status": source_parsing_audit.get("status"),
            "capability_kind_count": source_parsing_audit.get("capability_kind_count", 0),
            "indexed_file_count": source_parsing_audit.get("indexed_file_count", 0),
            "api_candidate_count": source_parsing_audit.get("api_candidate_count", 0),
            "interface_count": source_parsing_audit.get("interface_count", 0),
            "tutorial_count": source_parsing_audit.get("tutorial_count", 0),
            "finding_count": len(source_parsing_audit.get("findings", [])),
        },
        "source_ingestion_audit_status": {
            "status": source_ingestion_audit.get("status"),
            "source_count": source_ingestion_audit.get("source_count", 0),
            "fetch_source_count": source_ingestion_audit.get("fetch_source_count", 0),
            "manifest_source_count": source_ingestion_audit.get("manifest_source_count", 0),
            "indexed_file_count": source_ingestion_audit.get("indexed_file_count", 0),
            "evidence_card_count": source_ingestion_audit.get("evidence_card_count", 0),
            "finding_count": len(source_ingestion_audit.get("findings", [])),
        },
        "source_grounding_audit_status": {
            "status": source_grounding_audit.get("status"),
            "source_count": source_grounding_audit.get("source_count", 0),
            "evidence_card_count": source_grounding_audit.get("evidence_card_count", 0),
            "task_count": source_grounding_audit.get("task_count", 0),
            "rendered_markdown_count": source_grounding_audit.get("rendered_markdown_count", 0),
            "finding_count": len(source_grounding_audit.get("findings", [])),
        },
        "source_fetch_boundary_audit_status": {
            "status": source_fetch_boundary_audit.get("status"),
            "fetch_enabled": source_fetch_boundary_audit.get("fetch_enabled"),
            "source_count": source_fetch_boundary_audit.get("source_count", 0),
            "path_record_count": source_fetch_boundary_audit.get("path_record_count", 0),
            "finding_count": len(source_fetch_boundary_audit.get("findings", [])),
        },
        "environment_install_plan_status": {
            "status": environment_install_plan.get("status"),
            "plan_only": environment_install_plan.get("plan_only"),
            "install_strategy": environment_install_plan.get("install_strategy"),
            "missing_environment_fields": environment_install_plan.get("missing_environment_fields", []),
            "dependency_hint_count": len(environment_install_plan.get("dependency_hints", [])),
            "finding_count": len(environment_install_plan.get("findings", [])),
        },
        "resource_boundary_audit_status": {
            "status": resource_boundary_audit.get("status"),
            "resource_count": resource_boundary_audit.get("resource_count", 0),
            "risk_counts": resource_boundary_audit.get("risk_counts", {}),
            "finding_count": len(resource_boundary_audit.get("findings", [])),
        },
        "evidence_coverage_status": {
            "status": evidence_coverage.get("status"),
            "task_count": evidence_coverage.get("task_count", 0),
            "finding_count": len(evidence_coverage.get("findings", [])),
        },
        "evidence_precedence_status": {
            "status": evidence_precedence.get("status"),
            "task_count": evidence_precedence.get("task_count", 0),
            "finding_count": len(evidence_precedence.get("findings", [])),
        },
        "evidence_claim_taxonomy_audit_status": {
            "status": evidence_claim_taxonomy_audit.get("status"),
            "task_count": evidence_claim_taxonomy_audit.get("task_count", 0),
            "observed_claim_types": evidence_claim_taxonomy_audit.get("observed_claim_types", []),
            "finding_count": len(evidence_claim_taxonomy_audit.get("findings", [])),
        },
        "execution_trace_validation_status": {
            "status": execution_trace_validation.get("status"),
            "trace_count": execution_trace_validation.get("trace_count", 0),
            "valid_success_count": execution_trace_validation.get("valid_success_count", 0),
            "valid_success_trace_count": execution_trace_validation.get("valid_success_trace_count", 0),
            "valid_success_replay_result_count": execution_trace_validation.get("valid_success_replay_result_count", 0),
            "finding_count": len(execution_trace_validation.get("findings", [])),
        },
        "verification_claim_audit_status": {
            "status": verification_claim_audit.get("status"),
            "task_count": verification_claim_audit.get("task_count", 0),
            "trace_count": verification_claim_audit.get("trace_count", 0),
            "valid_success_count": verification_claim_audit.get("valid_success_count", 0),
            "finding_count": len(verification_claim_audit.get("findings", [])),
        },
        "execution_plan_status": {
            "execution_grounded_requested": execution_plan.get("execution_grounded_requested"),
            "missing_environment_fields": execution_plan.get("missing_environment_fields", []),
            "task_count": execution_plan.get("task_count", 0),
        },
        "tutorial_reproduction_plan_status": {
            "status": tutorial_reproduction_plan.get("status"),
            "execution_grounded_requested": tutorial_reproduction_plan.get("execution_grounded_requested"),
            "plan_only": tutorial_reproduction_plan.get("plan_only"),
            "tutorial_count": tutorial_reproduction_plan.get("tutorial_count", 0),
            "task_count": tutorial_reproduction_plan.get("task_count", 0),
            "replay_count": tutorial_reproduction_plan.get("replay_count", 0),
            "finding_count": len(tutorial_reproduction_plan.get("findings", [])),
        },
        "execution_replay_orchestrator_status": {
            "status": execution_replay_orchestrator.get("status"),
            "plan_only": execution_replay_orchestrator.get("plan_only"),
            "job_count": execution_replay_orchestrator.get("job_count", 0),
            "ready_job_count": execution_replay_orchestrator.get("ready_job_count", 0),
            "blocked_job_count": execution_replay_orchestrator.get("blocked_job_count", 0),
            "result_count": execution_replay_orchestrator.get("result_count", 0),
            "finding_count": len(execution_replay_orchestrator.get("findings", [])),
        },
        "contract_traceability_status": {
            "status": contract_traceability.get("status"),
            "record_count": contract_traceability.get("record_count", 0),
            "finding_count": len(contract_traceability.get("findings", [])),
        },
        "lineage_graph_status": {
            "status": lineage_graph.get("status"),
            "node_count": lineage_graph.get("node_count", 0),
            "edge_count": lineage_graph.get("edge_count", 0),
            "finding_count": len(lineage_graph.get("findings", [])),
        },
        "acceptance_suite_status": {
            "case_count": acceptance_suite.get("case_count", 0),
            "case_kinds": acceptance_suite.get("case_kinds", []),
        },
        "eval_splits_status": {
            "status": eval_splits.get("status"),
            "case_count": eval_splits.get("case_count", 0),
            "split_counts": eval_splits.get("split_counts", {}),
            "finding_count": len(eval_splits.get("findings", [])),
        },
        "eval_result_judge_status": {
            "status": eval_result_judge.get("status"),
            "result_count": eval_result_judge.get("result_count", 0),
            "pass_count": eval_result_judge.get("pass_count", 0),
            "fail_count": eval_result_judge.get("fail_count", 0),
            "unknown_count": eval_result_judge.get("unknown_count", 0),
        },
        "eval_leakage_audit_status": {
            "status": eval_leakage_audit.get("status"),
            "prompt_record_count": eval_leakage_audit.get("prompt_record_count", 0),
            "leaked_prompt_count": eval_leakage_audit.get("leaked_prompt_count", 0),
            "holdout_forward_scenario_count": eval_leakage_audit.get("holdout_forward_scenario_count", 0),
            "finding_count": len(eval_leakage_audit.get("findings", [])),
        },
        "agent_rollout_result_judge_status": {
            "status": agent_rollout_result_judge.get("status"),
            "result_count": agent_rollout_result_judge.get("result_count", 0),
            "pass_count": agent_rollout_result_judge.get("pass_count", 0),
            "fail_count": agent_rollout_result_judge.get("fail_count", 0),
            "unknown_count": agent_rollout_result_judge.get("unknown_count", 0),
            "finding_count": len(agent_rollout_result_judge.get("findings", [])),
        },
        "e2e_acceptance_status": {
            "status": e2e_acceptance.get("status"),
            "e2e_verdict": e2e_acceptance.get("e2e_verdict"),
            "require_e2e_acceptance": e2e_acceptance.get("require_e2e_acceptance"),
            "scenario_count": e2e_acceptance.get("scenario_count", 0),
            "required_scenario_count": e2e_acceptance.get("required_scenario_count", 0),
            "result_count": e2e_acceptance.get("result_count", 0),
            "passed_required_scenario_count": e2e_acceptance.get("passed_required_scenario_count", 0),
            "finding_count": len(e2e_acceptance.get("findings", [])),
        },
        "smoke_test_plan_status": {
            "status": smoke_test_plan.get("status"),
            "smoke_verdict": smoke_test_plan.get("smoke_verdict"),
            "require_smoke_test": smoke_test_plan.get("require_smoke_test"),
            "scenario_count": smoke_test_plan.get("scenario_count", 0),
            "result_count": smoke_test_plan.get("result_count", 0),
            "passed_scenario_count": smoke_test_plan.get("passed_scenario_count", 0),
            "finding_count": len(smoke_test_plan.get("findings", [])),
        },
        "draft_readiness_status": {
            "status": draft_readiness.get("status"),
            "checked_file_count": draft_readiness.get("checked_file_count", 0),
            "finding_count": len(draft_readiness.get("findings", [])),
        },
        "output_boundary_audit_status": {
            "status": output_boundary_audit.get("status"),
            "output_dir": output_boundary_audit.get("output_dir"),
            "child_skill_path": output_boundary_audit.get("child_skill_path"),
            "actual_public_file_count": len(output_boundary_audit.get("actual_public_files", [])),
            "finding_count": len(output_boundary_audit.get("findings", [])),
        },
        "skill_update_plan_status": {
            "status": skill_update_plan.get("status"),
            "plan_only": skill_update_plan.get("plan_only"),
            "discovery_decision": skill_update_plan.get("discovery_decision"),
            "recommended_action": skill_update_plan.get("recommended_action"),
            "missing_task_types": skill_update_plan.get("missing_task_types", []),
            "finding_count": len(skill_update_plan.get("findings", [])),
        },
        "skill_update_audit_status": {
            "status": skill_update_audit.get("status"),
            "plan_only": skill_update_audit.get("plan_only"),
            "recommended_action": skill_update_audit.get("recommended_action"),
            "merge_action_count": skill_update_audit.get("merge_action_count", 0),
            "finding_count": len(skill_update_audit.get("findings", [])),
        },
        "forward_test_plan_status": {
            "status": forward_test_plan.get("status"),
            "plan_only": forward_test_plan.get("plan_only"),
            "scenario_count": forward_test_plan.get("scenario_count", 0),
            "scenario_kinds": forward_test_plan.get("scenario_kinds", []),
            "finding_count": len(forward_test_plan.get("findings", [])),
        },
        "routing_fixture_status": {
            "case_count": routing_fixture.get("case_count", 0),
            "case_kinds": routing_fixture.get("case_kinds", []),
        },
        "grounding_gate_status": {
            "status": grounding_gate.get("status"),
            "task_count": len(grounding_gate.get("task_grounding", [])),
            "finding_count": len(grounding_gate.get("findings", [])),
        },
        "public_safety_audit_status": {
            "status": public_safety_audit.get("status"),
            "checked_file_count": public_safety_audit.get("checked_file_count", 0),
            "finding_count": len(public_safety_audit.get("findings", [])),
        },
        "claim_consistency_audit_status": {
            "status": claim_consistency_audit.get("status"),
            "checked_file_count": claim_consistency_audit.get("checked_file_count", 0),
            "task_count": claim_consistency_audit.get("task_count", 0),
            "finding_count": len(claim_consistency_audit.get("findings", [])),
        },
        "child_reference_coverage_status": {
            "status": child_reference_coverage.get("status"),
            "checked_file_count": child_reference_coverage.get("checked_file_count", 0),
            "task_count": child_reference_coverage.get("task_count", 0),
            "finding_count": len(child_reference_coverage.get("findings", [])),
        },
        "routing_metadata_audit_status": {
            "status": routing_metadata_audit.get("status"),
            "task_count": routing_metadata_audit.get("task_count", 0),
            "route_count": routing_metadata_audit.get("route_count", 0),
            "fixture_case_kinds": routing_metadata_audit.get("fixture_case_kinds", []),
            "finding_count": len(routing_metadata_audit.get("findings", [])),
        },
        "workflow_invariant_audit_status": {
            "status": workflow_invariant_audit.get("status"),
            "task_count": workflow_invariant_audit.get("task_count", 0),
            "checked_invariants": workflow_invariant_audit.get("checked_invariants", []),
            "finding_count": len(workflow_invariant_audit.get("findings", [])),
        },
        "requirement_coverage_status": {
            "status": requirement_coverage.get("status"),
            "requirement_count": requirement_coverage.get("requirement_count", 0),
            "covered_count": requirement_coverage.get("covered_count", 0),
            "finding_count": len(requirement_coverage.get("findings", [])),
        },
        "completion_evidence_audit_status": {
            "status": completion_evidence_audit.get("status"),
            "claim_verdict": completion_evidence_audit.get("claim_verdict"),
            "can_claim_full_goal_complete": completion_evidence_audit.get("can_claim_full_goal_complete"),
            "successful_execution_evidence_count": completion_evidence_audit.get("successful_execution_evidence_count", 0),
            "successful_execution_trace_count": completion_evidence_audit.get("successful_execution_trace_count", 0),
            "successful_execution_replay_result_count": completion_evidence_audit.get("successful_execution_replay_result_count", 0),
            "missing_evidence": completion_evidence_audit.get("missing_evidence", []),
            "finding_count": len(completion_evidence_audit.get("findings", [])),
        },
        "acceptance_handoff_status": {
            "status": acceptance_handoff.get("status"),
            "handoff_item_count": acceptance_handoff.get("handoff_item_count", 0),
            "target_request_fields": acceptance_handoff.get("target_request_fields", []),
            "finding_count": len(acceptance_handoff.get("findings", [])),
        },
        "api_surface_audit_status": {
            "status": api_surface_audit.get("status"),
            "allowed_symbol_count": api_surface_audit.get("allowed_symbol_count", 0),
            "code_fence_call_count": api_surface_audit.get("code_fence_call_count", 0),
            "inline_api_mention_count": api_surface_audit.get("inline_api_mention_count", 0),
            "finding_count": len(api_surface_audit.get("findings", [])),
        },
        "key_api_coverage_audit_status": {
            "status": key_api_coverage_audit.get("status"),
            "coverage_ratio": key_api_coverage_audit.get("coverage_ratio"),
            "required_key_api_count": key_api_coverage_audit.get("required_key_api_count", 0),
            "grounded_key_api_count": key_api_coverage_audit.get("grounded_key_api_count", 0),
            "finding_count": len(key_api_coverage_audit.get("findings", [])),
        },
        "task_quality": tasks,
        "task_blockers": task_blockers,
        "scorecards": scorecards,
        "policy": "Quality passes only when builder runtime audit, module inventory audit, builder baseline audit, skill package audit, request template audit, request audit, request fingerprint, external result contracts, phase state audit, review, lint, child metadata audit, draft readiness, output boundary, skill update planning, skill update audit, forward test planning, task partition decision log, task partition audit, discovery audit, discovery match audit, source parsing coverage, source parsing audit, source ingestion audit, environment install planning, resource boundary audit, review iteration log, review cursor, patch application, review optimizer state, patch safety, candidate selection, candidate promotion, final candidate audit, candidate evolution audit, review discipline, rubric grounding, review trajectory, execution trace validation, verification claim audit, tutorial reproduction planning, evidence coverage, evidence precedence, contract traceability, API surface audit, key API coverage audit, claim consistency, child reference coverage, routing metadata, workflow invariants, requirement coverage, completion evidence, acceptance handoff, lineage graph, eval splits, supplied eval results, eval leakage audit, supplied agent rollout results, artifact validation, code-fence audit, public safety audit, grounding gate, publish gate, acceptance suite, routing fixture, and task contracts have no blockers.",
    }
